First exercise
valentino-cachan/Challenge---HTML-CSS- pull request #1
Opened 2024-07-17 03:22 UTC by valentino-cachan

Screenshot

<img width="485" alt="image" src="https://github.com/user-attachments/assets/38b4c955-a3c6-40d5-a5a1-d060b890ade3" />

2024-07-17 03:24 UTC, facundo-cachan requested changes

2024-07-17 03:24 UTC, facundo-cachan commented on index.html
> +    <script src="https://cdn.tailwindcss.com?plugins=forms,typography"></script>
Remove JS

2024-07-17 03:24 UTC, facundo-cachan commented on index.html
> +		<script type="text/javascript">
Remove tailwind

2024-07-17 03:24 UTC, facundo-cachan commented on index.html
> +		<!-- <style type="text/tailwindcss">
Remove unused code

2024-07-17 03:24 UTC, facundo-cachan commented
Format code

2024-07-17 03:33 UTC, valentino-cachan commented on index.html
> +		<!-- <style type="text/tailwindcss">
fixed

2024-07-18 03:24 UTC, facundo-cachan approved these changes

2024-07-18 03:30 UTC, merged